server:
  port: 8002
spring:
  rabbitmq:
    host: ${RBMQ_HOST}
    port: 5672
    username: ${RBMQ_USER}
    password: ${RBMQ_PASS}
  mail:
    host: smtp.mailgun.org
    port: 587
    username: ${MAILGUN_USER}
    password: ${MAILGUN_PASS}
    default-encoding: UTF-8
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          from: welcome@vigourhub.com
        test-connection: false

mailgun:
  api-key: "asdfasdf"
  username: "asdfasdf"

