server:
  port: 8001
security:
  basic:
    enabled: false
spring:
  jpa:
    properties:
      hibernate:
        dll-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
      url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DATABASE}?stringtype=unspecified
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
  liquibase:
      change-log: db/migrations/master-changelog.yaml
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RBMQ_USER}
    password: ${RBMQ_PASSWORD}
keycloak:
  url: ${KEYCLOAK_URL}
  client: ${KEYCLOAK_SERVICE_ACCOUNT}
  secret: ${KEYCLOAK_SERVICE_ACCOUNT_SECRET}
  token-endpoint: "/auth/realms/vigourhub/protocol/openid-connect/token"
  users-endpoint: "/auth/admin/realms/vigourhub/users"
  validation-endpoint: "/auth/realms/vigourhub/protocol/openid-connect/userinfo"
  realm: "vigourhub"
  pubkey: ${KEYCLOAK_PUBLIC_KEY}
logging:
  level:
    org:
      hibernate:
        type: trace