version: "3.5"
services:
  main_db:
    image: postgres
    container_name: main_postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - ~/postgres/data/postgres-data:/var/lib/postgresql/data
  keycloak_postgres:
    image: postgres
    container_name: auth_server_db
    environment:
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - POSTGRES_DB=${KEYCLOAK_DB}
    volumes:
      - ~/keycloak-postgres/data/postgres-data:/var/lib/postgresql/data
    networks:
      - local-keycloak
  keycloak_auth:
    image: jboss/keycloak
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=keycloak_postgres
      - DB_USER=${KEYCLOAK_DB_USER}
      - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - DB_DATABASE=${KEYCLOAK_DB}
      - KEYCLOAK_USER=${KEYCLOAK_ADMIN}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    depends_on:
      - keycloak_postgres
    networks:
      - local-keycloak

networks:
  local-keycloak: