version: "3.5"
services:
  main_db:
    image: postgres
    container_name: main_postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - ~/vigourhub/postgres/data/postgres-data:/var/lib/postgresql/data
  redis_cache:
    image: redis
    container_name: redis_cache
    volumes:
      - ~/vigourhub/redis/data/redis:/var/lib/redis/data
    ports:
      - "6379:6379"
    command: >
      --requirepass ${REDIS_PASSWORD}
  rbmq-broker:
    image: rabbitmq
    container_name: rbmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RBMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RBMQ_PASSWORD}
    volumes:
        - ~/vigourhub/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/vigourhub/rabbitmq/log/:/var/log/rabbitmq
  keycloak_postgres:
    image: postgres
    container_name: auth_server_db
    environment:
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - POSTGRES_DB=${KEYCLOAK_DB}
    volumes:
      - ~/vigourhub/keycloak-postgres/data/postgres-data:/var/lib/postgresql/data
    networks:
      - local-keycloak
  keycloak_auth:
    image: jboss/keycloak
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=keycloak_postgres
      - DB_USER=${KEYCLOAK_DB_USER}
      - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - DB_DATABASE=${KEYCLOAK_DB}
      - KEYCLOAK_USER=${KEYCLOAK_ADMIN}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    depends_on:
      - keycloak_postgres
    networks:
      - local-keycloak

networks:
  local-keycloak: